<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="agilidev" failures="1" tests="1" name="Scenario_1" time="27.229" errors="0" timestamp="2025-10-19T20:09:59 CEST">
  <testcase classname="com.ats.executor.ActionTestScript" name="@AfterMethod cleanup" time="2.268">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.ats.recorder.TestSummary.getActions()&amp;quot; because &amp;quot;testSummary[0]&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.ats.recorder.TestSummary.getActions()" because "testSummary[0]" is null
at com.ats.tools.report.XmlReport.createReport(XmlReport.java:329)
at com.ats.recorder.VisualRecorder.terminate(VisualRecorder.java:163)
at com.ats.executor.ActionTestScript.setRecorder(ActionTestScript.java:1451)
at com.ats.executor.ActionTestScript.stopRecorder(ActionTestScript.java:1472)
at com.ats.executor.ActionTestScript.cleanup(ActionTestScript.java:673)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:836)
at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:805)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:781)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.TestNG.privateMain(TestNG.java:1430)
at org.testng.TestNG.main(TestNG.java:1394)
]]>
    </failure>
  </testcase> <!-- @AfterMethod cleanup -->
  <testcase classname="Scenario_1" name="Scenario_1" time="24.916">
    <failure type="com.ats.tools.logger.levels.AtsFailError" message="ActionAssertProperty (Scenario_1:2) -&amp;gt; {&amp;quot;app&amp;quot;:&amp;quot;msedge&amp;quot;,&amp;quot;errorCode&amp;quot;:-6,&amp;quot;errorMessage&amp;quot;:&amp;quot;property &amp;apos;text&amp;apos; with actual value &amp;apos;Linkedin&amp;apos; is not equals to &amp;apos;Linkedi&amp;apos; after 12203 ms&amp;quot;}">
      <![CDATA[com.ats.tools.logger.levels.AtsFailError: ActionAssertProperty (Scenario_1:2) -> {"app":"msedge","errorCode":-6,"errorMessage":"property 'text' with actual value 'Linkedin' is not equals to 'Linkedi' after 12203 ms"}
at com.ats.executor.ActionTestScript.actionFinished(ActionTestScript.java:1361)
at com.ats.executor.ActionTestScript.exec(ActionTestScript.java:1300)
at Scenario_1.TcScenario_1(Scenario_1.java:85)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.TestNG.privateMain(TestNG.java:1430)
at org.testng.TestNG.main(TestNG.java:1394)
]]>
    </failure>
  </testcase> <!-- Scenario_1 -->
</testsuite> <!-- Scenario_1 -->
